version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/dev/api/Dockerfile
    ports:
      - 8000:80
    depends_on:
      - db
    volumes:
      - ./api:/opt/api

  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
    driver: local
